services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/sql
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Optional: mount an init script if needed
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    shm_size: 4gb
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    deploy:
      resources:
        limits:
          memory: 32gb
        reservations:
          memory: 32gb

volumes:
  postgres_data:
    driver: local
    name: duckdb_test_postgres_data

networks:
  postgres_network:
    driver: bridge
    name: postgres_network
