services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/sql
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Optional: mount an init script if needed
    ports:
      - "5432:5432"
    networks:
      - postgres_network

volumes:
  postgres_data:
    driver: local
    name: duckdb_test_postgres_data

networks:
  postgres_network:
    driver: bridge
    name: postgres_network

